version: "3.8"
services:
  eq-tg-bot:
    build: ./tg-bot
    depends_on:
      - eq-aggregator
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - MONGO_URI=${MONGO_URI}
      - DB_NAMESPACE=${DB_NAMESPACE}
      - BOT_ENV=${BOT_ENV}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
  eq-aggregator:
    build: ./eq-aggregator
    environment:
      - WEBHOOK=http://eq-tg-bot:3000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"
