# fly.toml file generated for eq-aggregator on 2022-05-31T14:11:31+02:00

app = "eq-aggregator"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
