# fly.toml file generated for eq-tg-bot on 2022-05-31T14:57:41+02:00

app = "eq-tg-bot"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
