FROM --platform=$BUILDPLATFORM golang:latest as builder
ARG TARGETPLATFORM
ARG BUILDPLATFORM
ENV CGO_ENABLED=0

LABEL maintainer="Matija Pevec <pevec@live.com>"

WORKDIR /app

COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build -o /out/main .


FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root
COPY --from=builder /out/main .

ENV SOURCE "wss://www.seismicportal.eu/standing_order/websock"
ENV WEBHOOK "http://localhost:3300"

CMD ./main -source $SOURCE -webhook $WEBHOOK
