# fly.toml app configuration file generated for eq-tg-bot on 2023-05-23T19:41:45+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eq-tg-bot"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"
