# fly.toml file generated for eq-tg-bot on 2023-02-26T02:52:34+01:00

app = "eq-tg-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "Dockerfile"

[env]

[experimental]
  auto_rollback = true
